swagger: '2.0'
info:
  version: '1.0'
  title: orders_v1
  description: >
    Collection to test orders_v1 API Proxy

    Consumer: My Tele2 NL

    Provider: TIP; Siebel_NL
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: api.tele2.com:9006
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /nl/v1/oauth_nl/token:
    post:
      description: This API must be used to authenticate the user.
      summary: /v1/oauth_nl/token Get WSO2 auth token - Step 1
      tags:
      - Misc
      operationId: NlV1OauthNlTokenPost
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: client_id
        in: formData
        required: true
        type: string
        description: This field requires to have client id, this should be requested and provide by appigee/WSO2
      - name: client_secret
        in: formData
        required: true
        type: string
        description: This field requires to have client secret, this should be requested and provide by appigee/WSO2.
      - name: grant_type
        in: formData
        required: true
        type: string
        description: The values that can be send in this field is 'refresh_token' or 'password'.
      - name: username
        in: formData
        required: true
        type: string
        description: This field should contain the username. It is required when the grant type is password.
      - name: password
        in: formData
        required: true
        type: string
        description: This field should contain the password. It is required when the grant type is password.
      - name: X-Api-Key
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/~1v1~1oauthNl~1token get wso2 auth token - step 1response'
          examples:
            application/json:
              uid: 401203
              token_type: bearer
              expires_in: 2400
              refresh_token: 7bcbf7def9e2da21a4bbef6ef546e4
              access_token: 9f421e6e25599c53abdcede3dc35f8
              customer_type: 4G/LTE
              status: 200
              email: anamewpcftjgnsk16s11ptest0011@tele2.com
              role: Consumer
              msisdn: ''
              resellerShopId: ''
              applicationLinks:
              - id: 10313378919
                application: brite:bill
              - id: 10313378918
                application: siebel
              - id: ''
                application: cbs
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/orders/search:
    post:
      description: >-
        Gets the product detils for the customer.


        Note:

         Please get the latest access token before sending the request using the 'Get WSO2 auth token - Step 1' service present in the same folder.
      summary: /v1/orders/search
      tags:
      - Misc
      operationId: V1OrdersSearchPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/~1v1~1orders~1searchrequest'
      - name: X-Api-Key
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/~1v1~1orders~1searchresponse'
          examples:
            application/json:
              Status:
                StatusName: FAILURE
                StatusReason: No orders found
              PagingAndSorting:
                PageData:
                  PageSize: 20
                  TotalPages: 0
                  Index: 1
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  /v1/oauthNl/token get wso2 auth token - step 1response:
    title: /v1/oauth_nl/token Get WSO2 auth token - Step 1Response
    example:
      uid: 401203
      token_type: bearer
      expires_in: 2400
      refresh_token: 7bcbf7def9e2da21a4bbef6ef546e4
      access_token: 9f421e6e25599c53abdcede3dc35f8
      customer_type: 4G/LTE
      status: 200
      email: anamewpcftjgnsk16s11ptest0011@tele2.com
      role: Consumer
      msisdn: ''
      resellerShopId: ''
      applicationLinks:
      - id: 10313378919
        application: brite:bill
      - id: 10313378918
        application: siebel
      - id: ''
        application: cbs
    type: object
    properties:
      uid:
        description: ''
        example: 401203
        type: string
      token_type:
        description: ''
        example: bearer
        type: string
      expires_in:
        description: ''
        example: 2400
        type: string
      refresh_token:
        description: ''
        example: 7bcbf7def9e2da21a4bbef6ef546e4
        type: string
      access_token:
        description: ''
        example: 9f421e6e25599c53abdcede3dc35f8
        type: string
      customer_type:
        description: ''
        example: 4G/LTE
        type: string
      status:
        description: ''
        example: 200
        type: string
      email:
        description: ''
        example: anamewpcftjgnsk16s11ptest0011@tele2.com
        type: string
      role:
        description: ''
        example: Consumer
        type: string
      msisdn:
        description: ''
        type: string
      resellerShopId:
        description: ''
        type: string
      applicationLinks:
        description: ''
        example:
        - id: 10313378919
          application: brite:bill
        - id: 10313378918
          application: siebel
        - id: ''
          application: cbs
        type: array
        items:
          $ref: '#/definitions/ApplicationLink'
    required:
    - uid
    - token_type
    - expires_in
    - refresh_token
    - access_token
    - customer_type
    - status
    - email
    - role
    - msisdn
    - resellerShopId
    - applicationLinks
  ApplicationLink:
    title: ApplicationLink
    example:
      id: 10313378919
      application: brite:bill
    type: object
    properties:
      id:
        description: ''
        example: 10313378919
        type: string
      application:
        description: ''
        example: brite:bill
        type: string
    required:
    - id
    - application
  /v1/orders/searchrequest:
    title: /v1/orders/searchRequest
    example:
      CustomerOrderSearchRequest:
        OrderHeader:
          OrderId: 456
          Active: Y
          OrderType:
          - MSISDN Swap Order
          - Sales Order
          OrderSubType: ''
          OrderStatus: IN_PROGRESS
        OrderItem:
          ProductType: ''
          SubStatus: ''
          Status: ''
    type: object
    properties:
      CustomerOrderSearchRequest:
        $ref: '#/definitions/CustomerOrderSearchRequest'
    required:
    - CustomerOrderSearchRequest
  CustomerOrderSearchRequest:
    title: CustomerOrderSearchRequest
    example:
      OrderHeader:
        OrderId: 456
        Active: Y
        OrderType:
        - MSISDN Swap Order
        - Sales Order
        OrderSubType: ''
        OrderStatus: IN_PROGRESS
      OrderItem:
        ProductType: ''
        SubStatus: ''
        Status: ''
    type: object
    properties:
      OrderHeader:
        $ref: '#/definitions/OrderHeader'
      OrderItem:
        $ref: '#/definitions/OrderItem'
    required:
    - OrderHeader
    - OrderItem
  OrderHeader:
    title: OrderHeader
    example:
      OrderId: 456
      Active: Y
      OrderType:
      - MSISDN Swap Order
      - Sales Order
      OrderSubType: ''
      OrderStatus: IN_PROGRESS
    type: object
    properties:
      OrderId:
        description: ''
        example: 456
        type: string
      Active:
        description: ''
        example: Y
        type: string
      OrderType:
        description: ''
        example:
        - MSISDN Swap Order
        - Sales Order
        type: array
        items:
          type: string
      OrderSubType:
        description: ''
        type: string
      OrderStatus:
        description: ''
        example: IN_PROGRESS
        type: string
    required:
    - OrderId
    - Active
    - OrderType
    - OrderSubType
    - OrderStatus
  OrderItem:
    title: OrderItem
    example:
      ProductType: ''
      SubStatus: ''
      Status: ''
    type: object
    properties:
      ProductType:
        description: ''
        type: string
      SubStatus:
        description: ''
        type: string
      Status:
        description: ''
        type: string
    required:
    - ProductType
    - SubStatus
    - Status
  /v1/orders/searchresponse:
    title: /v1/orders/searchResponse
    example:
      Status:
        StatusName: FAILURE
        StatusReason: No orders found
      PagingAndSorting:
        PageData:
          PageSize: 20
          TotalPages: 0
          Index: 1
    type: object
    properties:
      Status:
        $ref: '#/definitions/Status'
      PagingAndSorting:
        $ref: '#/definitions/PagingAndSorting'
    required:
    - Status
    - PagingAndSorting
  Status:
    title: Status
    example:
      StatusName: FAILURE
      StatusReason: No orders found
    type: object
    properties:
      StatusName:
        description: ''
        example: FAILURE
        type: string
      StatusReason:
        description: ''
        example: No orders found
        type: string
    required:
    - StatusName
    - StatusReason
  PagingAndSorting:
    title: PagingAndSorting
    example:
      PageData:
        PageSize: 20
        TotalPages: 0
        Index: 1
    type: object
    properties:
      PageData:
        $ref: '#/definitions/PageData'
    required:
    - PageData
  PageData:
    title: PageData
    example:
      PageSize: 20
      TotalPages: 0
      Index: 1
    type: object
    properties:
      PageSize:
        description: ''
        example: 20
        type: string
      TotalPages:
        description: ''
        example: 0
        type: string
      Index:
        description: ''
        example: 1
        type: string
    required:
    - PageSize
    - TotalPages
    - Index
